### ISSUE TITLE
automatic archive enumeration

### ISSUE THREAD

**Issue by ltclm** [geoadmin/deploy#2]
When archive parameter -a is set but empty, the script should automatically generate an archive timestamp of format `YYYYMMDD`
`./deploy.sh -s bod_master -t dev -a` should generate `bod_masterYYYYMMDD`
`./deploy.sh -s bod_master -t dev -a mycustomsuffix`should generate `bod_mastermycustomsuffix``

**Comment by AFoletti** [comment]
Is this ticket still relevant?

**Comment by ltclm** [comment]
no thanks for pinging
